import type { ImageSourcePropType } from "react-native";

/**
 * Rider–Waite–Smith card art (public domain, see assets/CREDITS.md). Metro
 * needs static `require`s, hence the explicit table.
 */
export const TAROT_IMAGES: Record<string, ImageSourcePropType> = {
  major_00: require("../../../assets/tarot/major_00.jpg"),
  major_01: require("../../../assets/tarot/major_01.jpg"),
  major_02: require("../../../assets/tarot/major_02.jpg"),
  major_03: require("../../../assets/tarot/major_03.jpg"),
  major_04: require("../../../assets/tarot/major_04.jpg"),
  major_05: require("../../../assets/tarot/major_05.jpg"),
  major_06: require("../../../assets/tarot/major_06.jpg"),
  major_07: require("../../../assets/tarot/major_07.jpg"),
  major_08: require("../../../assets/tarot/major_08.jpg"),
  major_09: require("../../../assets/tarot/major_09.jpg"),
  major_10: require("../../../assets/tarot/major_10.jpg"),
  major_11: require("../../../assets/tarot/major_11.jpg"),
  major_12: require("../../../assets/tarot/major_12.jpg"),
  major_13: require("../../../assets/tarot/major_13.jpg"),
  major_14: require("../../../assets/tarot/major_14.jpg"),
  major_15: require("../../../assets/tarot/major_15.jpg"),
  major_16: require("../../../assets/tarot/major_16.jpg"),
  major_17: require("../../../assets/tarot/major_17.jpg"),
  major_18: require("../../../assets/tarot/major_18.jpg"),
  major_19: require("../../../assets/tarot/major_19.jpg"),
  major_20: require("../../../assets/tarot/major_20.jpg"),
  major_21: require("../../../assets/tarot/major_21.jpg"),
  wands_01: require("../../../assets/tarot/wands_01.jpg"),
  wands_02: require("../../../assets/tarot/wands_02.jpg"),
  wands_03: require("../../../assets/tarot/wands_03.jpg"),
  wands_04: require("../../../assets/tarot/wands_04.jpg"),
  wands_05: require("../../../assets/tarot/wands_05.jpg"),
  wands_06: require("../../../assets/tarot/wands_06.jpg"),
  wands_07: require("../../../assets/tarot/wands_07.jpg"),
  wands_08: require("../../../assets/tarot/wands_08.jpg"),
  wands_09: require("../../../assets/tarot/wands_09.jpg"),
  wands_10: require("../../../assets/tarot/wands_10.jpg"),
  wands_11: require("../../../assets/tarot/wands_11.jpg"),
  wands_12: require("../../../assets/tarot/wands_12.jpg"),
  wands_13: require("../../../assets/tarot/wands_13.jpg"),
  wands_14: require("../../../assets/tarot/wands_14.jpg"),
  cups_01: require("../../../assets/tarot/cups_01.jpg"),
  cups_02: require("../../../assets/tarot/cups_02.jpg"),
  cups_03: require("../../../assets/tarot/cups_03.jpg"),
  cups_04: require("../../../assets/tarot/cups_04.jpg"),
  cups_05: require("../../../assets/tarot/cups_05.jpg"),
  cups_06: require("../../../assets/tarot/cups_06.jpg"),
  cups_07: require("../../../assets/tarot/cups_07.jpg"),
  cups_08: require("../../../assets/tarot/cups_08.jpg"),
  cups_09: require("../../../assets/tarot/cups_09.jpg"),
  cups_10: require("../../../assets/tarot/cups_10.jpg"),
  cups_11: require("../../../assets/tarot/cups_11.jpg"),
  cups_12: require("../../../assets/tarot/cups_12.jpg"),
  cups_13: require("../../../assets/tarot/cups_13.jpg"),
  cups_14: require("../../../assets/tarot/cups_14.jpg"),
  swords_01: require("../../../assets/tarot/swords_01.jpg"),
  swords_02: require("../../../assets/tarot/swords_02.jpg"),
  swords_03: require("../../../assets/tarot/swords_03.jpg"),
  swords_04: require("../../../assets/tarot/swords_04.jpg"),
  swords_05: require("../../../assets/tarot/swords_05.jpg"),
  swords_06: require("../../../assets/tarot/swords_06.jpg"),
  swords_07: require("../../../assets/tarot/swords_07.jpg"),
  swords_08: require("../../../assets/tarot/swords_08.jpg"),
  swords_09: require("../../../assets/tarot/swords_09.jpg"),
  swords_10: require("../../../assets/tarot/swords_10.jpg"),
  swords_11: require("../../../assets/tarot/swords_11.jpg"),
  swords_12: require("../../../assets/tarot/swords_12.jpg"),
  swords_13: require("../../../assets/tarot/swords_13.jpg"),
  swords_14: require("../../../assets/tarot/swords_14.jpg"),
  pentacles_01: require("../../../assets/tarot/pentacles_01.jpg"),
  pentacles_02: require("../../../assets/tarot/pentacles_02.jpg"),
  pentacles_03: require("../../../assets/tarot/pentacles_03.jpg"),
  pentacles_04: require("../../../assets/tarot/pentacles_04.jpg"),
  pentacles_05: require("../../../assets/tarot/pentacles_05.jpg"),
  pentacles_06: require("../../../assets/tarot/pentacles_06.jpg"),
  pentacles_07: require("../../../assets/tarot/pentacles_07.jpg"),
  pentacles_08: require("../../../assets/tarot/pentacles_08.jpg"),
  pentacles_09: require("../../../assets/tarot/pentacles_09.jpg"),
  pentacles_10: require("../../../assets/tarot/pentacles_10.jpg"),
  pentacles_11: require("../../../assets/tarot/pentacles_11.jpg"),
  pentacles_12: require("../../../assets/tarot/pentacles_12.jpg"),
  pentacles_13: require("../../../assets/tarot/pentacles_13.jpg"),
  pentacles_14: require("../../../assets/tarot/pentacles_14.jpg"),
};

/** Width / height of the scans. */
export const TAROT_CARD_RATIO = 420 / 725;
